
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_ClusterDihedral cimport *

cdef _Action_ClusterDihedral * p = new _Action_ClusterDihedral()

del p
