
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_NativeContacts cimport *

cdef _Action_NativeContacts * p = new _Action_NativeContacts()

del p
