
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_MakeStructure cimport *

cdef _Action_MakeStructure * p = new _Action_MakeStructure()

del p
