
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_CreateReservoir cimport *

cdef _Action_CreateReservoir * p = new _Action_CreateReservoir()

del p
