
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Analysis_Integrate_py cimport *

cdef _Analysis_Integrate_py * p = new _Analysis_Integrate_py()

del p
