
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_GridFreeEnergy cimport *

cdef _Action_GridFreeEnergy * p = new _Action_GridFreeEnergy()

del p
