
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_DNAionTracker cimport *

cdef _Action_DNAionTracker * p = new _Action_DNAionTracker()

del p
