python ./test_cast_dataset.py 
python ./test_FrameList.py 
python ./test_teasing_traj.py 
python ./test_DataSet_double.py 
python ./test_Trajin_Single.py 
python ./test_FrameArray.py 
python ./test_Action_Surf.py 
python ./test_Frame.py 
python ./test_FrameArray_extensive_indexing.py 
python ./test_io.py 
python ./test_CpptrajFile.py 
python ./test_template.py 
python ./test_get_subframe.py 
python ./test_Residue.py 
python ./test_CpptrajState.py 
python ./test_Action_Radgyr.py 
python ./test_MolSurf.py 
python ./test_Trajectory.py 
python ./test_Topology.py 
python ./test_TrajectoryFile.py 
python ./test_ParmFile.py 
python ./test_iterload.py 
python ./test_AtomMask.py 
python ./test_load_indices.py 
python ./test_load_CHARMM.py 
python ./test_Trajout.py 
python ./test_Vec3.py 
python ./test_GridAction.py 
python ./test_DistRoutines.py 
python ./test_writepdb.py 
python ./test_indexing_speed.py 
python ./test_DataSet_Coords_TRJ.py 
python ./test_DataSet_Coords_CRD.py 
python ./test_Trajin_Single_iter.py 
python ./test_dummy_indexing_FrameArray.py 
python ./test_TopologyList.py 
python ./test_DataSetList.py 
python ./test_Trajin.py 
python ./test_FrameArray2.py 
python ./test_base.py 
python ./test_Action_Strip.py 
python ./test_loadingtime.py 
