
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_CheckStructure cimport *

cdef _Action_CheckStructure * p = new _Action_CheckStructure()

del p
