
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_STFC_Diffusion cimport *

cdef _Action_STFC_Diffusion * p = new _Action_STFC_Diffusion()

del p
