
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_VelocityAutoCorr cimport *

cdef _Action_VelocityAutoCorr * p = new _Action_VelocityAutoCorr()

del p
