
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_MultiDihedral cimport *

cdef _Action_MultiDihedral * p = new _Action_MultiDihedral()

del p
