
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_SymmetricRmsd cimport *

cdef _Action_SymmetricRmsd * p = new _Action_SymmetricRmsd()

del p
