
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_RandomizeIons cimport *

cdef _Action_RandomizeIons * p = new _Action_RandomizeIons()

del p
