
# distutils: language = c++
# this test file was automatically generated by ./make_test_auto.py
from Action_OrderParameter cimport *

cdef _Action_OrderParameter * p = new _Action_OrderParameter()

del p
