import numpy as np

def load(fname, shape=()):
    """Load trajectory generated by cpptraj"""
    arr = np.loadtxt(fname, skiprows=1).flatten().reshape(shape)
    return arr

if __name__ == "__main__":
    arr = load("./data/stripAllButCA.Tc5b.x", (10, 60))
    print arr[0]
